language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PACKAGE="scry"
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.04.2
   - DISTRO=debian-testing OCAML_VERSION=4.05.0
   - DISTRO=debian-unstable OCAML_VERSION=4.04.0
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0
   - DISTRO=alpine OCAML_VERSION=4.06.0
