lib: [
  "_build/install/default/lib/scry/META" {"META"}
  "_build/install/default/lib/scry/opam" {"opam"}
  "_build/install/default/lib/scry/scry__Repo.cmi"
  "_build/install/default/lib/scry/scry__Repo.cmx"
  "_build/install/default/lib/scry/scry__Repo.cmt"
  "_build/install/default/lib/scry/repo.ml"
  "_build/install/default/lib/scry/scry__Result.cmi"
  "_build/install/default/lib/scry/scry__Result.cmx"
  "_build/install/default/lib/scry/scry__Result.cmt"
  "_build/install/default/lib/scry/result.ml"
  "_build/install/default/lib/scry/scry.cmi"
  "_build/install/default/lib/scry/scry.cmx"
  "_build/install/default/lib/scry/scry.cmt"
  "_build/install/default/lib/scry/scry.ml-gen"
  "_build/install/default/lib/scry/scry__Time.cmi"
  "_build/install/default/lib/scry/scry__Time.cmx"
  "_build/install/default/lib/scry/scry__Time.cmt"
  "_build/install/default/lib/scry/time.ml"
  "_build/install/default/lib/scry/scry.cma"
  "_build/install/default/lib/scry/scry.cmxa"
  "_build/install/default/lib/scry/scry.a"
  "_build/install/default/lib/scry/scry.cmxs"
]
bin: [
  "_build/install/default/bin/ocaml-scry" {"ocaml-scry"}
]
doc: [
  "_build/install/default/doc/scry/README.md"
]
